# Generated by Django 6.0.4 on 2026-05-02 20:02

import datetime
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='inventory',
            old_name='quantity',
            new_name='current_level',
        ),
        migrations.RemoveField(
            model_name='inventory',
            name='max_level',
        ),
        migrations.RemoveField(
            model_name='inventory',
            name='min_level',
        ),
        migrations.RemoveField(
            model_name='menuitem',
            name='restaurant',
        ),
        migrations.RemoveField(
            model_name='reservation',
            name='reservation_date',
        ),
        migrations.RemoveField(
            model_name='reservation',
            name='reservation_time',
        ),
        migrations.RemoveField(
            model_name='reservation',
            name='total_price',
        ),
        migrations.AddField(
            model_name='inventory',
            name='reorder_level',
            field=models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=10),
        ),
        migrations.AddField(
            model_name='menuitem',
            name='restaurants',
            field=models.ManyToManyField(related_name='menu_items', to='restaurant.restaurant'),
        ),
        migrations.AddField(
            model_name='reservation',
            name='reservation_datetime',
            field=models.DateTimeField(default=datetime.datetime(2026, 5, 2, 20, 2, 31, 272014, tzinfo=datetime.timezone.utc)),
            preserve_default=False,
        ),
    ]
