# Generated by Django 6.0.4 on 2026-05-02 21:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0003_remove_menuitem_is_available_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='table',
            name='status',
            field=models.IntegerField(choices=[(1, 'Available'), (2, 'Occupied'), (3, 'Reserved'), (4, 'Needs Cleaning')], default=1),
        ),
    ]
