# Generated by Django 6.0.4 on 2026-05-05 20:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0007_alter_restaurant_latitude_alter_restaurant_longitude'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staffinvite',
            name='role',
            field=models.IntegerField(choices=[(1, 'Manager'), (2, 'Server Host'), (3, 'Kitchen Staff'), (4, 'Delivery Driver'), (5, 'Customer'), (6, 'Owner')]),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.IntegerField(choices=[(1, 'Manager'), (2, 'Server Host'), (3, 'Kitchen Staff'), (4, 'Delivery Driver'), (5, 'Customer'), (6, 'Owner')]),
        ),
    ]
