# Generated by Django 6.0.4 on 2026-05-06 04:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0008_alter_staffinvite_role_alter_user_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_active_staff',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='user',
            name='phone_number',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='shift_end',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='shift_start',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
