# Generated by Django 6.0.4 on 2026-05-07 15:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0009_user_is_active_staff_user_phone_number_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='table',
            name='assigned_server',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_tables', to=settings.AUTH_USER_MODEL),
        ),
    ]
