# Generated by Django 6.0.4 on 2026-05-16 18:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0011_order_table_order_tax_amount_payment_status_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ManagerNote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField()),
                ('target_role', models.IntegerField(choices=[(0, 'All Staff'), (1, 'Managers'), (2, 'Servers / Hosts'), (3, 'Kitchen Staff'), (4, 'Delivery Drivers'), (6, 'Owners')], default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField()),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('restaurant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='manager_notes', to='restaurant.restaurant')),
            ],
        ),
        migrations.CreateModel(
            name='PreOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('special_instruction', models.TextField(blank=True, null=True)),
                ('status', models.IntegerField(choices=[(1, 'Pending'), (2, 'Activated'), (3, 'Cancelled')], default=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('customer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='restaurant.customer')),
                ('reservation', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='preorder', to='restaurant.reservation')),
                ('restaurant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='restaurant.restaurant')),
            ],
        ),
        migrations.CreateModel(
            name='PreOrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField()),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('menu_item', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='restaurant.menuitem')),
                ('preorder', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='restaurant.preorder')),
            ],
        ),
        migrations.CreateModel(
            name='TableTransferRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.IntegerField(choices=[(1, 'Pending'), (2, 'Accepted'), (3, 'Declined')], default=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('receiving_server', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='incoming_transfer_requests', to=settings.AUTH_USER_MODEL)),
                ('requesting_server', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='outgoing_transfer_requests', to=settings.AUTH_USER_MODEL)),
                ('table', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transfer_requests', to='restaurant.table')),
            ],
        ),
    ]
