# Generated by Django 6.0.4 on 2026-05-16 18:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0012_managernote_preorder_preorderitem_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='notification_type',
            field=models.IntegerField(choices=[(1, 'Order Ready'), (2, 'Order Cancelled'), (3, 'Table Attention')], default=1),
        ),
    ]
